apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: core-app-webapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: core-app-webapi
    spec:
      containers:
      - name: core-app-webapi
        image: patobelardo/coreappsample-webapi
        ports:
        - containerPort: 80
          name: http
