apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: core-app-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: core-app-mongo
    spec:
      containers:
      - name: core-app-mongo
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo
apiVersion: v1
kind: Service
metadata:
  name: core-app-mongo
spec:
  ports:
  - port: 6379
  selector:
    app: core-app-mongo
