apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: core-app-frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: core-app-frontend
    spec:
      containers:
      - name: core-app-frontend
        image: patobelardo/coreappsample-frontend
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: core-app-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: core-app-frontend